server:
  port: 8080

spring:
  main:
    banner-mode: off
    
app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/customerdb
    username: postgres
    password: password
    pool-size: 30
